"""first init

Revision ID: 76f07d4d2507
Revises: 
Create Date: 2021-05-11 17:39:24.165015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f07d4d2507'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Köpekler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isim', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Oyuncaklar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oyuncak_ismi', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['Köpekler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sahip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['Köpekler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sahip')
    op.drop_table('Oyuncaklar')
    op.drop_table('Köpekler')
    # ### end Alembic commands ###
